immunomind/immunarch

DESCRIPTION
R/io-parsers.R
R/io-utility.R
R/io.R
vignettes/v2_data.Rmd

- CATT format parser
- RTCR, Imseq and Vidjil formats detection; RTCR parser WIP (existing problem: missing D gene column)
- first working version of RTCR parser
- Imseq format parser
- Vidjil format parser
- added columns for CDR1 and CDR2 to MiXCR parser
- v2_data.Rcmd update

Parsers for new data formats

---

R/io-utility.R

Fix for error that parser failed on files with only header, without data

Fix for error that parser failed on files without data

---

R/filters.R

Filtering data and metadata by conditions on metadata

CALC-108-new-filtering

---

R/filters.R
R/tools.R

* Better input validation for repFilter
* Removed input data classes in repFilter

Fixes for repFilter

---

R/vis.R

Bugfix of issue when additional pheatmap arguments cannot be used in 'heatmap2' method of vis

Fix of multiple arguments handling in vis

---

R/overlap.R

Overlap description was updated - .downsampling argument described more clear and return values section were updated

Fix repOverlap description

---

R/immunr_data_format.R
R/io-parsers.R

C gene alignments are now parsed from MiXCR format in repLoad

Support for C gene alignments in MiXCR format

---

R/vis.R
man/seqCluster.Rd
man/vis_heatmap.Rd

vis_heatmap() now has parameter .axis.text.size

Support for changing text size for heatmaps

---

R/germline.R
R/tools.R
man/repAlignLineage.Rd
man/repGermline.Rd

1. Detect V.end and J.start automatically if missing;
2. Germline now contains reference sequences both for V and J chains;
3. Added warnings about too short V and/or J sequences;
4. Updated docs for repGermline.

Germline algorithms update

---

R/germline.R
R/seqCluster.R
man/seqCluster.Rd

Fix for trimming intersections of V and J with CDR3 in Germline

Germline formulas fix

---

R/diversity.R

Fix for https://github.com/immunomind/immunarch/issues/147#issuecomment-1099327604

Diversity error fix

---

DESCRIPTION
R/io-utility.R

Avoid crashing in if() when detecting format if input file is empty

Better empty file handling

---

DESCRIPTION
R/overlap.R
man/repOverlap.Rd

Noted that only 1st method is used

repOverlap docs update

---

R/io-parsers.R
R/io.R
man/repLoad.Rd

repLoad fixes

---

R/germline.R
README.md
man/repGermline.Rd
vignettes/v1_introduction.Rmd
vignettes/web_only/BCRpipeline.Rmd

Fixes for PR https://github.com/immunomind/immunarch/pull/249

Germline alignment PR fixes

---

R/align_lineage.R
R/phylip.R
man/repAlignLineage.Rd
man/repClonalFamily.Rd

Added columns for each clonotype that are required to calculate somatic hypermutation

BCR functions update

---

R/align_lineage.R
R/phylip.R
R/somatic_hypermutation.R

Updates for PHYLIP parser needed for visualization

Phylip output parser update

---

vignettes/web_only/BCRpipeline.Rmd

SHM description

---

tests/testthat/test-germline.R

Tests for repGermline() function

repGermline tests

---

R/distance.R
R/seqCluster.R

seqDist() and seqCluster() support for optional gene names trimming

Update for seqDist and seqCluster

---

R/io-parsers.R
R/io.R
man/repLoad.Rd

Support for MiXCR 4.1 format and manual count column selection

MiXCR format update

---

R/diversity.R

Fix for bug reported in https://github.com/immunomind/immunarch/issues/281

repDiversity bugfixes

---

R/io-parsers.R
R/tools.R

Fix for https://github.com/immunomind/immunarch/issues/315

10x filt_contigs fix

---

tests/testthat/test-clonal-family.R
tests/testthat/test-somatic-hypermutation.R

- Tests for repClonalFamily()
- fix
- SHM tests

Tests for repClonalFamily() and repSomaticHypermutation()
